### ISSUE TITLE
Introduce Visualization Tools for Training Metrics

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#13]
Implement functions to plot training metrics (loss, accuracy) over time for better tracking and debugging.

**Objective**:  
Provide users with visual feedback on model training and performance.

**Implementation Suggestions**:  
- Create a `Plotting` utility class with methods for loss and accuracy plots.
- Use libraries like Matplotlib or Seaborn for visualization.
- Allow users to specify what metrics to visualize and save plots as images.

**Comment by SujitSakore** [comment]
Hello @ravin-d-27 will you please assign me this one.

**Comment by ravin-d-27** [comment]
Hi @SujitSakore ! Thank you for your interest !  I am assigning this issue to you !

**Comment by SujitSakore** [comment]
Hello @ravin-d-27  I have resolved the issue https://github.com/ravin-d-27/PyDeepFlow/issues/13 If there are any changes or further adjustments needed, please let me know. I would appreciate it if you could accept my pull request.
