### ISSUE TITLE
Add Support for Advanced Activation Functions

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#15]
Integrate more advanced activation functions like Swish and ELU for better performance on deeper networks.

**Objective**:  
Enhance model expressiveness and performance.

**Implementation Suggestions**:  
- Implement additional activation functions in the activation module.
- Provide options to choose these functions in model configurations.
- Test and benchmark new activations against existing ones.

**Comment by Sohammhatre10** [comment]
Hello @ravin-d-27 will you please assign me this one.

**Comment by ravin-d-27** [comment]
Hi @Sohammhatre10 ! I'm assigning this issue to you!
