### ISSUE TITLE
Implement Cross-Validation Support

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#16]
Add support for k-fold cross-validation to ensure the model generalizes well across different subsets of data.

**Objective**:  
Improve model evaluation and robustness against overfitting.

**Implementation Suggestions**:  
- Create a `CrossValidator` class that implements k-fold cross-validation.
- Allow users to specify the number of folds and metrics for evaluation.
- Provide detailed output on performance across folds.

**Comment by GGital** [comment]
Hello @ravin-d-27! I would like to contribute in your repo in this topic. I would like to know if you still need additional functions or details as I see you already implemented the CrossValidator class. You can also suggest me other features if wanted!

**Comment by ravin-d-27** [comment]
Hi @GGital ! Thank you for your interest!
I want to test if this functionality is working or not. So could you please create a file called `cross_validation_runner.py` and check whether it's working or not?

If it's working, make a PR of `cross_validation_runner.py` file, else fix the problem and make a PR.

**Comment by GGital** [comment]
Hi @ravin-d-27! Thank you for your reply! I would like to ask you few questions before I proceed this.
1. I want to know if there is any edits in the `requirements.txt` file. I can't use those dependencies to run `runner.py`. 
2. There is already a K-fold usage in `runner.py` at the moment. I don't know if there is still any requirement for me to work with this. If there is no need for the `cross_validation_runner.py` anymore, you can assign me another task as I am finding a repo about DL/ML to contribute with in this Hacktoberfest.
3. Can you also assign me for this issue as well?

**Comment by ravin-d-27** [comment]
Hi @GGital. 
There are no edits as of now. Only thing is if you are using PyDeepFlow with the help of GPU, you need to install cupy.

`pip install cupy`.

Other than that the `requirements.txt` is correct and functional. To avoid conflicts with your other dependencies in your python, consider using a virtual environment.

I also understand that there is no need for this issue as most of the things are already implemented. Testing is the only part which is remaining (Which I will do it).

So, I would like to assign another issue to you. Please check out the other issues and let me know which one you would like to work. 

Thank you for your interest !
