### ISSUE TITLE
Output Probabilities in Predictions

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#2]
Add a new function, `predict_prob()`, to the `model.py` file that returns predicted probability scores, enhancing the model's interpretability. Ensure the function is thoroughly tested with at least two datasets (available in the `datasets` folder) before creating a pull request (PR).

**Comment by G0v1ndD3v** [comment]
Hi, I'm currently studying Data Science and found this project really interesting. I'd love to give this issue a try. Could you please assign it to me?

**Comment by ravin-d-27** [comment]
Hi @G0v1ndD3v . That's great. Will assign you this issue !
