### ISSUE TITLE
Detailed documentation of PyDeepFlow 

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#21]
You have to make a detailed documentation on how to use PyDeepFlow. It should contain all the necessary functions for implementing a model and description of all the hyperparameters.

Please add all the documentation in a new file named `Documentation.md`

**Comment by G0v1ndD3v** [comment]
Hi, just a suggestion regarding the documentation for PyDeepFlow. While creating a `Documentation.md` file is a good approach, a GitHub Wiki might be more effective. A Wiki allows for better organization with hierarchical sections like "Getting Started" or "Hyperparameters," making navigation easier. A Wiki also offers flexibility for quick updates, encourages community contributions, and keeps the codebase cleaner by separating documentation from the code.

**Comment by G0v1ndD3v** [comment]
Hi, just a suggestion regarding the documentation for PyDeepFlow. While creating a `Documentation.md` file is a good approach, a GitHub Wiki might be more effective. A Wiki allows for better organization with hierarchical sections like "Getting Started" or "Hyperparameters," making navigation easier. It also offers flexibility for quick updates, encourages community contributions, and keeps the codebase cleaner by separating documentation from the code.

**Comment by ravin-d-27** [comment]
Hi @G0v1ndD3v. This idea seems to be nice. Will check it out and update you regarding this.

**Comment by G0v1ndD3v** [comment]
Hey, just following up on the idea I proposed. Any updates? 🙂

**Comment by ravin-d-27** [comment]
Hi @G0v1ndD3v , sorry, I completely forgot about this 😅. Will get back to you !

**Comment by ravin-d-27** [comment]
Hi @G0v1ndD3v , thank you for this wonderful idea. 

Based on that, I made some plan of action for the Documentation.

- A **"Home"** page will serve as the main entry point, providing an overview of the PyDeepFlow project and links to different sections.
- A **"Getting Started"** page to explain installation and setup instructions.
- A **"Core Functions"** page to document all the necessary functions for implementing a model.
- A **"Hyperparameters"** page that details all hyperparameters, explaining their significance and how to use them.
- Additional sections like **"Examples"** and **"Advanced Features"** can be added as needed.

What's your view on this?

**Comment by G0v1ndD3v** [comment]
The plan for the Wiki looks great! I’m happy to help if you need any assistance while working on it. 🙂

**Comment by ravin-d-27** [comment]
Thank you @G0v1ndD3v !
