### ISSUE TITLE
Add Regularization Techniques

### ISSUE THREAD

**Issue by ravin-d-27** [ravin-d-27/PyDeepFlow#3]
Create a new Python file that implements both L2 regularization and dropout, giving users the flexibility to enable or disable these features by adjusting parameters. Ensure all relevant parameters are included for customization. 

Verify that the model continues to learn effectively after adding L2 and dropout layers, and thoroughly test the implementation using at least two datasets from the `datasets` folder before submitting a pull request (PR).

**Comment by G0v1ndD3v** [comment]
I’d like to take this on. I have a good understanding of the code and have contributed before. Could you please assign it to me?

**Comment by ravin-d-27** [comment]
Thanks for your interest ! Sure!

**Comment by ravin-d-27** [comment]
@G0v1ndD3v , please pull the changes before start to working on, because I have made some changes in the code.
